# Generated by Django 4.2.15 on 2024-08-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('remote_ip', models.CharField(max_length=20)),
                ('remote_user', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=100)),
                ('response_code', models.CharField(max_length=100)),
                ('response_size', models.IntegerField()),
                ('referrer', models.CharField(blank=True, max_length=100, null=True)),
                ('agent', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
